<a href="https://colab.research.google.com/github/zeeshan3106/7News-Melbourne/blob/main/XGBoost%20Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
california = fetch_california_housing(as_frame=True)
california = california.frame
california
X = california.drop(columns=['MedHouseVal'])
y = california['MedHouseVal']
X.head(2)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.02381,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.97188,2401.0,2.109842,37.86,-122.22

In [34]:
import xgboost as xgb
from sklearn.metrics import mean_absolute_error
xgb = xgb.XGBRegressor(n_estimators=200, random_state=42, learning_rate=0.3)
train = xgb.fit(X,y)
test = xgb.predict(X)
mean_absolute_error(y,test)*100

15.170040400022868

In [57]:
new_data = X.iloc[11:12,:]
new_data
xgb.predict(new_data)

array([2.591027], dtype=float32)

In [58]:
california.iloc[11:12,:]

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
11,3.2705,52.0,4.77248,1.024523,1504.0,2.049046,37.85,-122.26,2.418